### ISSUE TITLE
PullToRefresh created programmatically does not set winControl correct

### ISSUE THREAD

**Issue by pke** [dwcares/TouchControls#3]
I think this line https://github.com/dwcares/TouchControls/blob/master/TouchControls/touchControls.js#L8

needs to be `this.element.winControl = this`

**Comment by dwcares** [comment]
Explain...

Sent from my Windows Phone

**Comment by pke** [comment]
Well, otherwise when u create the control by code, it will not have the winControl property set? Cause u set it on element, which can be null.
